#Server
server.port= 8088
server.servlet.context-path=/api

#Configuracion del FrontEnd
cors.allowed-origins=http://localhost:4200

#Configuracion de Keycloack
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/dm-dev
keycloak.auth-server-url=http://localhost:8080
keycloak.client-id=dm-client-api-rest
keycloak.realm=dm-dev
keycloak.client-secret=SLXomEV0H7qwZoLwaMElgdA5R0XbjlIZ
logging.level.org.keycloak=DEBUG
jwt.auth.converter.resource-id=dm-client-api-rest
jwt.auth.converter.principle-attribute=preferred_username

#Configuracion DB
spring.datasource.url=jdbc:postgresql://localhost:5432/dm_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

#Configuración de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#Mostrar consultas SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Actuator
management.endpoints.web.exposure.include=health,info,loggers

